=== IuliiaH/languagetool-mirror/rules/rules.dtd
<!--
Grammar Rules DTD
Daniel Naber, daniel.naber@t-online.de, 2001-12-21
$id: $

This DTD defines a format for 
 -grammar rules
 -false friends
 -deprecated words

The DTD is designed in a way that false friends can be
used in both ways, e.g. 'actual' is a false friend for
speakers of German, and 'aktuell' is a false friend for
speakers of English who write a text in German. The file
is not limited to English/German but can actually be 
extended to any number of languages, hopefully with minimal
redundancy.

Note for grammar rules:

* One of the examples should be type="correct",
  one should be type="incorrect". This contraint is
  not part of the DTD. The first two examples will
  be shown to the user. All examples will be used
  for the test cases.
* It's often difficult to says if an error is a  grammar errors or
  'just' a typo, so we have not attribute for that.

-->

<!ENTITY % Languages "(en|de|fr)">

<!ELEMENT rules (rule|rulegroup)*>

<!ELEMENT rulegroup (message?,error_rate?,rule+)>
<!ATTLIST rulegroup id ID #REQUIRED>
<!ATTLIST rulegroup name CDATA #IMPLIED>

<!ELEMENT rule ( pattern,
	((message?,error_rate?,example,example+) | 
	(translation+,message?,example*)) )>
<!ATTLIST rule id ID #IMPLIED>	<!-- well, required but not if there's a group -->
<!ATTLIST rule level (0|1|2|3|4|5|6|7|8|9|10) #IMPLIED>
<!ATTLIST rule name CDATA #IMPLIED>

<!ELEMENT pattern (#PCDATA)>
<!ATTLIST pattern lang %Languages; #REQUIRED>
<!ATTLIST pattern case_sensitive (yes|no) #IMPLIED>
<!ATTLIST pattern mark_from CDATA #IMPLIED>
<!ATTLIST pattern mark_to CDATA #IMPLIED>

<!ELEMENT translation (#PCDATA)>
<!ATTLIST translation lang %Languages; #REQUIRED>

<!-- message shown to the user if a rule matches: -->
<!ELEMENT message (#PCDATA|em)*>

<!-- percentage of sentences tagged as wrong in BNC: -->
<!ELEMENT error_rate EMPTY>
<!-- number of (real or unreal) warnings when testing BNC sentences: -->
<!ATTLIST error_rate warnings CDATA #IMPLIED>
<!-- number of BNC sentences used to get 'warnings': -->
<!ATTLIST error_rate sentences CDATA #IMPLIED>

<!ELEMENT example (#PCDATA|em)*>
<!ATTLIST example type (correct|incorrect|triggers_error) #REQUIRED>
<!-- used to explain 'triggers_error': -->
<!ATTLIST example reason CDATA #IMPLIED>

<!-- emphasis of the most significant part: -->
<!ELEMENT em (#PCDATA)>

=== IuliiaH/languagetool-mirror/rules/enwords.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE rules PUBLIC "-//W3C//DTD GrammarRules 0.1//EN" "rules.dtd">
<!--
Rules: Words that should not be used
(c) 2001,2002,2003 Daniel Naber, daniel.naber@t-online.de, 2001-12-30
$Id: enwords.xml,v 1.1 2004-05-23 21:46:20 dnaber Exp $
-->
<rules>

	<!-- fixme: add >'s< (but only as VBZ, not POS) too -->
	<!-- the tokenizer splits "don't" into "do n't" because the tagger needs
		it that way, so we use two tokens: -->
	<rule id="SHORT_FORMS_NOT" name="Avoid short forms (don't etc.)">
		<pattern lang="en">".*" "n't"</pattern>
		<message>Suggestion: use a long form like <em>do not</em> instead of <em>don't</em> for formal texts.</message>
		<example type="correct"><em>Do not</em> open the box unless you've read the instructions.</example>
		<example type="incorrect"><em>Don't</em> open the box unless you've read the instructions.</example>
	</rule>
	
	<rule id="SHORT_FORMS_WILL" name="Avoid short forms (I'll etc.)">
		<pattern lang="en">".*" "'ll"</pattern>
		<message>Suggestion: use a long form like <em>\1 will</em> instead for formal texts.</message>
		<example type="correct"><em>He will</em> open the box.</example>
		<example type="incorrect"><em>He'll</em> open the box.</example>
	</rule>

	<rule id="SHORT_FORMS_HAVE" name="Avoid short forms (we've etc.)">
		<pattern lang="en">".*" "'ve"</pattern>
		<message>Suggestion: use a long form like <em>\1 have</em> instead for formal texts.</message>
		<example type="correct">Questions <em>we have</em> asked some people.</example>
		<example type="incorrect">Questions <em>we've</em> asked some people.</example>
	</rule>

	<rule id="SHORT_FORMS_ARE" name="Avoid short forms (we're etc.)">
		<pattern lang="en">".*" "'re"</pattern>
		<message>Suggestion: use a long form like <em>\1 are</em> instead for formal texts.</message>
		<example type="correct">What <em>We Are</em> Reading</example>
		<example type="incorrect">What <em>We're</em> Reading</example>
	</rule>

	<rule id="OR_SENT_START" name="Avoid 'Or' at the beginning of a sentence">
		<pattern lang="en" mark_from="0" mark_to="-1">SENT_START "or"</pattern>
		<message>Suggestion: don't start a sentence with <em>or</em>.</message>
		<example type="correct"><em>Instead</em>, one could think about other approaches.</example>
		<example type="incorrect"><em>Or</em> one could think about other approaches.</example>
	</rule>

	<rule id="BILLION" name="Avoid 'billion'">
		<pattern lang="en">"billion"</pattern>
		<message>Suggestion: use <em>thousand million</em> instead of billion to avoid ambiguities.</message>
		<example type="correct">Feds "Misplaced" $17.3 <em>Thousand Million</em> Last Year</example>
		<example type="incorrect">Feds "Misplaced" $17.3 <em>Billion</em> Last Year</example>
	</rule>

</rules>
